export const USER_SIGNIN_REQUEST='USER_SIGNIN-REQUEST';
export const USER_SIGNIN_SUCCESS='USER_SIGNIN-SUCCESS';
export const USER_SIGNIN_FAIL='USER_SIGNIN-FAIL';

export const USER_LIST_REQUEST='USER_LIST_REQUEST';
export const USER_LIST_SUCCESS='USER_LIST_SUCCESS';
export const USER_LIST_FAIL='USER_LIST_FAIL';

export const USER_DETAILS_REQUEST='USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS='USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAIL='USER_DETAILS_FAIL';

export const USER_SAVE_REQUEST='USER_SAVE_REQUEST';
export const USER_SAVE_SUCCESS='USER_SAVE_SUCCESS';
export const USER_SAVE_FAIL='USER_SAVE_FAIL';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';

export const USER_REGISTER_REQUEST='USER_REGISTER-REQUEST';
export const USER_REGISTER_SUCCESS='USER_REGISTER-SUCCESS';
export const USER_REGISTER_FAIL='USER_REGISTER-FAIL';

export const USER_LOGOUT = 'USER_LOGOUT';